name: NEWS RADAR

on:
  schedule:
    - cron: "3,18,33,48 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: news-radar-publisher
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Получить файлы
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Запустить публикацию
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: "@newsRadar2026"
          POSTS_PER_RUN: "1"
        run: python app.py

      - name: Сохранить posted.json
        run: |
          git config user.name "news-radar-bot"
          git config user.email "actions@users.noreply.github.com"

          git add posted.json

          if git diff --cached --quiet; then
            echo "Новых изменений нет"
            exit 0
          fi

          git commit -m "Update published news"
          git pull --rebase origin main
          git push origin main
